# Generated by Django 4.2.4 on 2023-10-26 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_location_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Profile_image',
            new_name='profile_image',
        ),
    ]
